version: "3.9"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    restart: always
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=apigateway,cloudformation,es,iam,lambda,s3,sts
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - /tmp/localstack
