version: "3.9"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack-full
    restart: always
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=apigateway,cloudformation,es,iam,lambda,s3,sts
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=./.localstack
      - PORT_WEB_UI=9000
      - DEBUG=true
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
